### ISSUE TITLE
Bitsteam Generation

### ISSUE THREAD

**Issue by CLappin** [RISCV-on-Microsemi-FPGA/M2S150-Advanced-Dev-Kit#4]
A minor issue has been found in the MIV_RV32IMA_L1_AHB_BaseDesign Libero Project.
The check box  to program the FPGA fabric is not set. A new project will be uploaded asap.

In the mean time to fix this issue, go to the Design Flow, right click Generate Bitstream, select Configure Bitsream and select Fabric. Then re-generate the bitstream only. This should not effect the SmartDesign, Synthesis or Place and Route or Generate FPGA Array Data.

**Comment by kevinscully100** [comment]
Merged pull request #5 from CLappin/master
